apiVersion: v1
kind: Service
metadata:
  name: ro-service
spec:
  selector:
    app: ro-service
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
      nodePort: 30011
  type: NodePort
